# Generated by Django 4.0.6 on 2022-07-18 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnionLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=256, null=True, unique=True)),
                ('onion_id', models.CharField(max_length=56, unique=True, validators=[django.core.validators.RegexValidator('^[a-z2-7]{56}$')])),
                ('status', models.PositiveIntegerField(choices=[(0, 'Active'), (1, 'Pending deletion')], db_index=True, default=1)),
                ('config_index', models.PositiveIntegerField()),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('physical_folder_path', models.FilePathField(allow_files=False, allow_folders=True, null=True)),
            ],
        ),
    ]
